apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered
  namespace: smarthome
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: smarthome-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - nodered.local
    secretName: nodered-tls
  rules:
  - host: nodered.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodered
            port:
              number: 1880
