apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ejbca
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guylavian/smarthome.git
    targetRevision: HEAD
    path: base/ejbca
  destination:
    server: https://kubernetes.default.svc
    namespace: ejbca
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
