apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ejbca
  namespace: ejbca
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: smarthome-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - ejbca.local
    secretName: ejbca-tls
  rules:
  - host: ejbca.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ejbca
            port:
              number: 8080
