apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ejbca
resources:
  - namespace.yaml
  - mariadb-secret.yaml
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - ejbca-pvc.yaml
  - ejbca-deployment.yaml
  - ejbca-service.yaml
  - ejbca-ingress.yaml
